### ISSUE TITLE
Error in benchmark for native omit

### ISSUE THREAD

**Issue by victor-homyakov** [Berkmann18/NativeVsUtils#2]
## Expected behaviour
Benchmark for `_.omit()` omits two fields `age` and `active` from the object. Benchmark for native alternative should look like `const { age, active, ...res } = users[1];`.

## Actual behaviour
Benchmark for native code looks for non-existent fields `a`, `c`: `const { a, c, ...res } = users[1];`. Therefore two benchmarks cannot be compared.

## How to reproduce

https://jsfiddle.net/2fjyLuc6/

## Possible solution(s)

Fix the benchmarks
- https://github.com/Berkmann18/NativeVsUtils/blob/c4ad4175375eb0ba345c03536dc8d860de2626ff/index.js#L406-L412
- https://github.com/Berkmann18/NativeVsUtils/blob/c4ad4175375eb0ba345c03536dc8d860de2626ff/nativeVsLodash.js#L365-L370
- https://github.com/Berkmann18/NativeVsUtils/blob/c4ad4175375eb0ba345c03536dc8d860de2626ff/lodash.js#L197

## Environment
-   Version: 
-   OS(s): 
-   Browser(s) (if applicable): 
-   Node version: 
-   NPM version:

**Comment by Berkmann18** [comment]
Hi @victor-homyakov, thanks for pointing that out, I'll fix that and update what I can.

**Comment by victor-homyakov** [comment]
@Berkmann18 This may affect benchmark results. Could you please refresh comparisons and images?

**Comment by Berkmann18** [comment]
I updated some of it, but the process was done manually, and I'll need to check if the automated approach I implemented is correct (feel free to have a look at it).
I have quite a lot to do at the moment so I won't have time to do that for a few weeks.
